version: "3.7"

services:
    # backend:
    #     container_name: backend
    #     build:
    #         context: .
    #         dockerfile: ./backend/dev.Dockerfile
    #     volumes:
    #         - ./backend:/backend
    #     ports:
    #         - 8000:3000

    db:
        image: mongo:latest
        container_name: database
        environment:
            - MONGO_DATA_DIR=/data/db
        #    - MONGO_LOG_DIR=/dev/null
        volumes:
            - data-volume:/data/db
        ports:
            - 27017:27017
        #command: mongod --logpath=/dev/null # --quiet

volumes:
    data-volume: