version: "3.7"

services:
    backend:
        container_name: sweet-up-backend
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./backend:/backend
        ports:
            - 8080:8080

    db:
        image: mongo:latest
        container_name: database
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - data-volume:/data/db
        ports:
            - 27017:27017

volumes:
    data-volume: